# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Seasons', models.CharField(choices=[('S', 'Summer'), ('W', 'Winter'), ('M', 'Monsoon')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('Long', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('HID', models.AutoField(primary_key=True, serialize=False)),
                ('Long', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Income', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Bi'), ('G', 'Gay'), ('L', 'Lesbian'), ('T', 'Trans')], max_length=1)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('PHID', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=200)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=200)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('WID', models.AutoField(primary_key=True, serialize=False)),
                ('Long', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=6)),
                ('AvgYield', models.DecimalField(decimal_places=6, max_digits=6)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='WellWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('measured_date', models.DateField(default=datetime.date.today)),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wells')),
            ],
        ),
        migrations.AddField(
            model_name='farms',
            name='HID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses'),
        ),
        migrations.AddField(
            model_name='crops',
            name='FID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farms'),
        ),
    ]
