# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:01
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('Type', models.CharField(choices=[('WID', 'WID'), ('FID', 'FID'), ('HID', 'HID')], max_length=3)),
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Rice', max_length=50)),
                ('Year', models.IntegerField()),
                ('Seasons', models.CharField(choices=[('S', 'Summer'), ('W', 'Winter'), ('M', 'Monsoon')], max_length=20)),
                ('Area', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('plot', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('area', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('HID', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.FloatField(default=0.0)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=30)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('Type', models.CharField(choices=[('WID', 'WID'), ('FID', 'FID'), ('HID', 'HID')], max_length=3)),
                ('PHID', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_images/')),
                ('FID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Farms')),
                ('HID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('Type', models.CharField(choices=[('WID', 'WID'), ('FID', 'FID'), ('HID', 'HID')], max_length=3)),
                ('VID', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='uploaded_video/')),
                ('FID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Farms')),
                ('HID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('WID', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), srid=4326)),
                ('AvgYield', models.DecimalField(decimal_places=4, max_digits=7)),
                ('Depth', models.DecimalField(decimal_places=4, max_digits=7)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses')),
            ],
        ),
        migrations.CreateModel(
            name='Yields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yield', models.FloatField(default=0.0)),
                ('measured_date', models.DateField(default=datetime.date.today)),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wells')),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='WID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Wells'),
        ),
        migrations.AddField(
            model_name='photos',
            name='WID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Wells'),
        ),
        migrations.AddField(
            model_name='farms',
            name='HID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Houses'),
        ),
        migrations.AddField(
            model_name='crops',
            name='FID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farms'),
        ),
        migrations.AddField(
            model_name='audios',
            name='FID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Farms'),
        ),
        migrations.AddField(
            model_name='audios',
            name='HID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Houses'),
        ),
        migrations.AddField(
            model_name='audios',
            name='WID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Wells'),
        ),
    ]
