# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wells',
            name='HID',
        ),
        migrations.AddField(
            model_name='wells',
            name='FID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Farms'),
            preserve_default=False,
        ),
    ]
