# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170831_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
